### PR TITLE
feat(interface): expose blob shape and capacity

### PR DESCRIPTION
**Pull request by hobofan**
We need both of these exposed to make dimension checking work in leaf.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request
- Commit: 939bde9cc6cb686c8c8f8c3f89feeb70433c7a4c
  - Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

Guidelines are available at https://github.com/autumnai/phloem

---

This message was auto-generated by https://gitcop.com

**Comment by hobofan** [comment]
@homu +r

**Comment by hobofan** [comment]
@homu r+

**Comment by GitCop** [comment]
There were the following issues with your Pull Request
- Commit: 939bde9cc6cb686c8c8f8c3f89feeb70433c7a4c
  - Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

Guidelines are available at https://github.com/autumnai/phloem

---

This message was auto-generated by https://gitcop.com

**Comment by hobofan** [comment]
@homu r+

**Comment by hobofan** [comment]
@homu r+

**Comment by hobofan** [comment]
@homu r+

**Pull request merged**
