### PR TITLE
chore/versioning: fix clippy version constrains

### PR DESCRIPTION
**Pull request by MichaelHirn**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request
- Commit: 42fc3b7e89970857ab1fc2ec03e9a09d1350a6ad
  - Commits must be in the following format: **%{type}/%{scope}: %{description}**

Guidelines are available at https://github.com/autumnai/leaf/blob/develop/CONTRIBUTING.md#git-commit-guidelines

---

This message was auto-generated by https://gitcop.com

**Comment by MichaelHirn** [comment]
@homu r+

**Comment by MichaelHirn** [comment]
@homu r+

**Comment by MichaelHirn** [comment]
@homu r+

**Comment by MichaelHirn** [comment]
@homu retry

**Comment by MichaelHirn** [comment]
@homu r+

**Comment by MichaelHirn** [comment]
@homu r+

**Comment by MichaelHirn** [comment]
@homu r+

**Comment by MichaelHirn** [comment]
@homu r+

**Pull request merged**
